### ISSUE TITLE
Need to publish a new release to npm

### ISSUE THREAD

**Issue by ajthenewguy** [rustwasm/create-wasm-app#13]
I am following along this tutorial: https://rustwasm.github.io/book/game-of-life/hello-world.html

At the "Putting it into a Webpage" step the following command fails:

```
$ npm init wasm-app
command not found: create-wasm-app
```

**Comment by fitzgen** [comment]
Thanks for the bug report @ajthenewguy!

We need to publish a new version to npm, as this is fixed on master, but the only person who can do that is on vacation at the moment :-p

In the meantime, this is equivalent to `npm init wasm-app www`, and should let you continue the tutorial:

```
git clone git@github.com:rustwasm/create-wasm-app.git www
```

I'll leave this issue open until we get a new release published.

**Comment by ajthenewguy** [comment]
Thanks @fitzgen !
Running the following worked:
`git clone https://github.com/rustwasm/create-wasm-app.git www`

**Comment by fitzgen** [comment]
Oh! Apparently I have npm access! Published and verified that `npm init wasm-app www` works.

Thanks again @ajthenewguy :)
