### ISSUE TITLE
express with wasm

### ISSUE THREAD

**Issue by nesteg** [rustwasm/create-wasm-app#27]
I'm trying your example integrate into my application written with using express framework but get error in browser(Firefox v.60)
"Loading failed for module with source “http://localhost:3000/public/javascripts/bootstrap.js”
html:
" <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello wasm-pack!</title>
  </head>
  <body>
    <script type="module" src="../public/javascripts/bootstrap.js"></script>
  </body>
</html>"

In Folder public/javascript next files unchanged as an example:
 bootstrap.js
 HelloWasm_bg.wasm
 HelloWasm.d.ts
 HelloWasm.js
 index.js

WebAssembly is cool!!!Help me!

**Comment by ashleygwilliams** [comment]
hi @nesteg - that error usually happens because there's a path issue somewhere in your code. were you careful to update all of the filenames/paths to your new HelloWasm module? if you could push up a repo i would be able to take a look!

**Comment by nesteg** [comment]
I'm understand.It all worked out.
Thank you!!
